### PR TITLE
A bunch of updates and new packages

### PR DESCRIPTION
**Pull request by paaguti**
Merry XMas and all the best for 2019!

### CODE REVIEW

**Comment by ruda** [comment]
Thank you for this great contribution!
For consistency, when you're changing the ports,
please put the port name in beginning of the commit message,
then put : follow by the message, examples:

xz: update to version 5.2.4
pcr2: adopt version 10.32

Put every port change in one different commit.

Besides that, looks good.

**Comment by ruda** [comment]
Rebase your code , I've applied some commits your provide in this pull request.

**Comment by paaguti** [comment]
I hope I was able to rebase (first time I did this :-) ) Happy New Year
q

**Comment by ruda** [comment]
We need to close this pull request. I will include all of packages's updates and adoptions that you have made so far, as long as I think it makes sense for the project.

Any changes in Rudix.mk or files related (the build system) I will not apply, I suggest first to open the discussion in the Issue, then we can think the better approach to change the build system.

Also, you can create a new pull quest for including and/or update new ports/packages. Don't need to use this pull request, because it became very big and confusing.

You can use one pull request for port's updates ou adaptions, but using one for many is OK too.

Again, Thank you very much for dedication and work! Happy 2019.

**Comment by paaguti** [comment]
I think the PatchLevel variable makes a lot of sense and is more or less trivial. 
That and the sorting of the patches should go in ASAP because they make patching strait-forward.

Take a look at how the Makefiles are simplified by them. You start not needing a define when -p1 us needed and can get your patches from quilt 

Re CMake, OK, let’s plan it better

Enviado desde mi iPhone

**Pull request closed without merging**
