### PR TITLE
Merged with upstream and included sort order for patches again

### PR DESCRIPTION
**Pull request by paaguti**
Hi

I really think coding the patch sorting order in the files and not in Makefile is more than handy. I have included a link that explains how to fix the order in $(wildcard.

Seeing the order of the patches with the xyz-<descriptor>.patch file naming convention autodocuments, and should be more intuitive than having to write a hook when you have several patches to apply in order to guarantee the patch order

### CODE REVIEW

**Comment by ruda** [comment]
> Hi
> 
> I really think coding the patch sorting order in the files and not in Makefile is more than handy. I have included a link that explains how to fix the order in $(wildcard.

Hello, there isn't anything disallowing you to use some numeric prefix to apply patches in order. The Rudix.mk makefile you look for patches in current directory and inside the patches/.
I notice that also using *.diff as a name of patch is a good thing, so I'm gonna also consider *.patch and *.diff as well.

> 
> Seeing the order of the patches with the xyz-.patch file naming convention autodocuments, and should be more intuitive than having to write a hook when you have several patches to apply in order to guarantee the patch order

Documentation is lack, I don't have much to do with it now.

**Comment by ruda** [comment]
If you want to make a suggestion, the best way is to create a new issue for that feature, because a bunch of commits are very difficult for the maintainer to track.

**Comment by paaguti** [comment]
Ok, I’ll do that

Enviado desde mi iPhone

**Comment by ruda** [comment]
We need to think hardly about this merge request! It is very difficult to me to handle it. I usually take some parts (commits) of your work and do it manually on the master (this is `git cherry-pick thing)`. I really appreciate your work, but I could not manage it.

I'm thinking of a way to help you to collaborate easily.

**Comment by paaguti** [comment]
Never mind,

I try to keep my repo updated with yours and recommit as much as possible. I understand that there are things that may not be general interest ;-)

/PA

Enviado desde mi iPad

**Comment by paaguti** [comment]
I did it again... :-) I'm using TexLive a lot and there are some utilities that depend on the libraries installed by XQuartz. I have just pushed the libs needed to compile libXext, needed by MetaFont.

**Pull request closed without merging**
